.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH handlr-open 1  "handlr-open " 
.SH NAME
handlr-regex\-open - Open a path/URL with its default handler
.SH SYNOPSIS
\fBhandlr open\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIPATHS\fR> 
.SH DESCRIPTION
Open a path/URL with its default handler
.PP
Unlike xdg\-open and similar resource openers, multiple paths/URLs may be supplied.
.PP
If multiple handlers are set and `enable_selector` is set to true, you will be prompted to select one using `selector` from ~/.config/handlr/handlr.toml. Otherwise, the default handler will be opened.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
<\fIPATHS\fR>
Paths/URLs to open
