.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH handlr-mime 1  "handlr-mime " 
.SH NAME
handlr-regex\-mime - Get the mimetype of a given file/URL
.SH SYNOPSIS
\fBhandlr mime\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-\-json\fR] [\fIPATHS\fR] 
.SH DESCRIPTION
Get the mimetype of a given file/URL
.PP
By default, output is in the form of a table that matches file paths/URLs to their mimetypes.
.PP
When using `\-\-json`, output will be in the form:
.PP
```json
.PP
[
.PP
{
.PP
"path": "README.md"
.PP
"mime": "text/markdown"
.PP
},
.PP
{
.PP
"path": "https://duckduckgo.com/"
.PP
"mime": "x\-scheme\-handler/https"
.PP
}
.PP
\&...
.PP
]
.PP
```
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
\fB\-\-json\fR
Output mimetype info as json
.TP
[\fIPATHS\fR]
File paths/URLs to get the mimetype of
