.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH handlr-list 1  "handlr-list " 
.SH NAME
handlr-regex\-list - List default apps and the associated handlers
.SH SYNOPSIS
\fBhandlr list\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-a\fR|\fB\-\-all\fR] 
.SH DESCRIPTION
List default apps and the associated handlers
.PP
Output is formatted as a table with two columns. The left column shows mimetypes and the right column shows the handlers
.PP
Currently does not support regex handlers.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information
.TP
\fB\-a\fR, \fB\-\-all\fR
Expand wildcards in mimetypes and show global defaults
